services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=1234
        ports:
            - 5432:5432
        volumes:
            - /var/lib/postgresql/data
    mongodb:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=null
        ports:
            - 27017:27017
        volumes:
            - /var/lib/mongodb/data
    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
            - 5672:5672
            - 15672:15672
    auction-svc:
        image: rahuld1999/auction-svc:latest
        build:
            context: .
            dockerfile: AuctionService/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80
            - RabbitMq__Host=rabbitmq
            - ConnectionStrings__DefaultConnection=Server=postgres;Port=5432;User Id=postgres;Password=1234;Database=auctions
            - IdentityServiceUrl=http://identity-svc
        ports:
            - 7001:80
        depends_on:
            - postgres
            - rabbitmq
    search-svc:
        image: rahuld1999/search-svc:latest
        build:
            context: .
            dockerfile:  src/SearchService/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80
            - RabbitMq__Host=rabbitmq
            - ConnectionStrings__MongoDbConnection=mongodb://localhost:27017@mongodb
            - AuctionServiceUrl=http://auction-svc
        ports:
            - 7002:80
        depends_on:
            - mongodb
            - rabbitmq